group("benchmark") {
  deps = [
    ":drag_benchmark",
    ":render_benchmark",
    ":resize_benchmark",
    ":scroll_benchmark",
    ":startup_benchmark",
    "//benchmark/smoothness",
  ]
  if (is_mac) {
    deps += [
      ":benchmark_analyzer",
      ":move_mouse",
    ]
  }
}

executable("drag_benchmark") {
  sources = [ "drag_benchmark.cc" ]
  deps = [ "//px" ]
}

executable("render_benchmark") {
  sources = [ "render_benchmark.cc" ]
  deps = [ "../ui:retained_text" ]

  if (is_mac) {
    defines = [ "GL_SILENCE_DEPRECATION" ]
  }
}

executable("resize_benchmark") {
  sources = [
    "resize_benchmark.cc",
    "resize_sweep.h",
  ]
  deps = [
    "//fx",
    "//px",
  ]
}

executable("scroll_benchmark") {
  sources = [
    "scroll_benchmark.cc",
    "smoothness/timed_input.h",
  ]
  if (is_mac) {
    sources += [ "smoothness/timed_input_mac.mm" ]
  } else {
    sources += [ "smoothness/timed_input_portable.cc" ]
  }
  deps = [
    "//benchmark/smoothness:scroll_trace_data",
    "//px",
    "//ui:retained_text",
    "//ui:smooth_scroll",
  ]
}

executable("startup_benchmark") {
  sources = [ "startup_benchmark.cc" ]
  deps = [ "//ui:window" ]
}

if (is_mac) {
  executable("benchmark_analyzer") {
    sources = [ "analyzer.mm" ]

    frameworks = [
      "AVFoundation.framework",
      "CoreMedia.framework",
      "CoreVideo.framework",
      "Foundation.framework",
    ]
  }

  executable("move_mouse") {
    sources = [ "move_mouse.cc" ]
    frameworks = [ "ApplicationServices.framework" ]
  }
}
