group("all") {
  deps = [
    "//benchmark",
    "//conformance",
    "//simple_text",

    # TODO: Think about how we should structure perf tests. Loose executables
    # are probably fine, but we need to organize them somehow.
    "//base:unicode_perftest",
    "//fx:fx_glyph_cache_perftest",
    "//fx:fx_perftest",
  ]
}

group("tests") {
  testonly = true
  deps = [
    "//testing:perf_tests",
    "//testing:unit_tests",
  ]
}

group("experiments") {
  deps = [
    "//experiments/canary",
    "//experiments/examples",
    "//experiments/fuzz",
    "//experiments/playground",
    "//experiments/rope",
  ]

  if (is_mac) {
    deps += [ "//experiments/mac_startup_benchmark" ]
  }
}
