#!/bin/bash

ninja -C out/arm64
ninja -C out/x64

rm -rf out/universal
mkdir -p out/universal

# https://chromium.googlesource.com/chromium/src/+/main/docs/mac_arm64.md#universal-builds
./scripts/universalizer.py \
  out/arm64/Simple\ Text.app \
  out/x64/Simple\ Text.app \
  out/universal/Simple\ Text.app
