import("//build/config/mac/icon.gni")
import("//build/config/mac/mac_app_bundle.gni")

common_sources = [
  "editor_app.cc",
  "editor_app.h",
  "editor_window.cc",
  "editor_window.h",
  "main.cc",
]

common_deps = [
  "//base",
  "//font",
  "//gl",
  "//gui",
  "//third_party/spdlog",
]

if (is_mac) {
  mac_app_bundle("simple_text") {
    output_name = "Simple Text"
    bundle_identifier = "com.jason5122.simple-text"
    info_plist = "resources/Info.plist"

    sources = common_sources
    deps = common_deps

    # deps += [ ":icon" ]
  }

  # icon("icon") {
  #   sources = [ "resources/app.iconset" ]
  # }
} else if (is_linux) {
  executable("simple_text") {
    sources = common_sources
    deps = common_deps
  }
} else if (is_win) {
  executable("simple_text") {
    sources = common_sources
    deps = common_deps

    configs -= [ "//build/config/win:console" ]
    configs += [ "//build/config/win:windowed" ]
  }
}
