source_set("gtest") {
  testonly = true

  public_deps = [ "//third_party/googletest:gtest" ]

  if (is_mac) {
    sources = [
      "gtest_mac.h",
      "gtest_mac.mm",
    ]

    frameworks = [ "Foundation.framework" ]
  }
}

group("fuzztest") {
  testonly = true
  public_deps = [
    ":gtest",
    "//third_party/fuzztest:init_fuzztest",
  ]
}

executable("unit_tests") {
  testonly = true

  sources = [ "main.cc" ]
  if (is_mac) {
    sources += [ "gtest_mac_unittest.mm" ]
  }

  deps = [
    ":fuzztest",
    "//base:base_unittests",
    "//editor:editor_unittests",
    "//experiments/fuzztest_demo",
    "//font:font_unittests",
  ]
}

executable("perf_tests") {
  testonly = true

  sources = [ "main.cc" ]

  deps = [
    ":fuzztest",
    "//base:base_perftests",
    "//editor:editor_perftests",
    "//font:font_perftests",
  ]
}
