source_set("editor") {
  sources = [
    "buffer/piece_tree.cc",
    "buffer/piece_tree.h",
    "buffer/red_black_tree.cc",
    "buffer/red_black_tree.h",
    "movement.cc",
    "movement.h",
    "search/ac_fast.cc",
    "search/ac_fast.h",
    "search/ac_slow.cc",
    "search/ac_slow.h",
    "search/aho_corasick.cc",
    "search/aho_corasick.h",
    "selection.h",
  ]

  public_deps = [ "//font" ]

  deps = [
    "//base",
    "//third_party/spdlog",
    "//third_party/uni_algo",
  ]
}

source_set("editor_unittests") {
  testonly = true

  sources = [
    "buffer/piece_tree_unittest.cc",
    "buffer/red_black_tree_unittest.cc",
    "buffer/tree_walker_unittest.cc",
    "movement_unittest.cc",
    "search/aho_corasick_unittest.cc",
  ]

  deps = [
    ":editor",
    "//base",
    "//font",
    "//testing:gtest",
    "//third_party/spdlog",
    "//third_party/uni_algo",
  ]
}

source_set("editor_perftests") {
  testonly = true

  sources = [
    "buffer/piece_tree_perftest.cc",
    "buffer/red_black_tree_perftest.cc",
    "search/aho_corasick_perftest.cc",
  ]

  deps = [
    ":editor",
    "//base",
    "//testing:gtest",
  ]
}
