executable("rasterizer") {
  sources = [
    "font_core_text.cc",
    "main.mm",
  ]

  frameworks = [
    "CoreText.framework",
    "CoreGraphics.framework",
    "CoreFoundation.framework",
    "ImageIO.framework",
    "AppKit.framework",
  ]

  # TODO: Enable this.
  # configs += [ "//build/config/compiler:prevent_unsafe_narrowing" ]

  deps = [
    "//base",
    "//third_party/spdlog",
  ]
}
