executable("rasterizer") {
  sources = [
    "atlas.cc",
    "font_core_text.cc",
    "gl_renderer.mm",
    "layout.cc",
    "rasterizer.cc",
  ]

  inputs = [
    "glyph_vert.glsl",
    "glyph_frag.glsl",
  ]

  frameworks = [
    "CoreText.framework",
    "CoreGraphics.framework",
    "CoreFoundation.framework",
    "AppKit.framework",
    "QuartzCore.framework",
    "OpenGL.framework",
  ]
  defines = [ "GL_SILENCE_DEPRECATION" ]

  configs += [ "//build/config/compiler:prevent_unsafe_narrowing" ]

  deps = [
    ":capture",
    "//base",
    "//third_party/spdlog",
    "//third_party/uni_algo",
  ]
}

executable("capture_server") {
  sources = [ "capture_server.cc" ]

  configs += [ "//build/config/compiler:prevent_unsafe_narrowing" ]

  deps = [
    ":capture",
    "//third_party/spdlog",
  ]
}

source_set("capture") {
  sources = [
    "capture.h",
    "capture.mm",
  ]

  framework_dirs = [ "/System/Library/PrivateFrameworks" ]
  frameworks = [
    "AppKit.framework",
    "CoreFoundation.framework",
    "CoreGraphics.framework",
    "ImageIO.framework",
    "SkyLight.framework",
  ]

  configs += [ "//build/config/compiler:prevent_unsafe_narrowing" ]
}
