source_set("base") {
  sources = [
    "check.cc",
    "check.h",
    "compiler_specific.h",
    "containers/fixed_flat_map.h",
    "containers/flat_map.h",
    "containers/flat_tree.h",
    "containers/span_util.h",
    "debug/profiler.h",
    "debug/timer.h",
    "files/file.h",
    "files/file_path.cc",
    "files/file_path.h",
    "files/file_reader.cc",
    "files/file_reader.h",
    "files/file_util.cc",
    "files/file_util.h",
    "files/scoped_file.h",
    "functional/scope_exit.h",
    "hash/hash.h",
    "location.cc",
    "location.h",
    "memory/atomic_flag.h",
    "memory/atomic_ref_count.h",
    "memory/ref_counted.h",
    "memory/scoped_refptr.h",
    "memory/weak_ptr.h",
    "message_loop/message_pump.cc",
    "message_loop/message_pump.h",
    "no_destructor.h",
    "numeric/safe_conversions.h",
    "numeric/saturation_arithmetic.h",
    "path_service.cc",
    "path_service.h",
    "posix/eintr_wrapper.h",
    "rand_util.cc",
    "rand_util.h",
    "strings/string_util.cc",
    "strings/string_util.h",
    "strings/sys_string_conversions.h",
    "strings/utf_string_conversions.cc",
    "strings/utf_string_conversions.h",
    "third_party/icu/icu_utf.h",
    "time/time.h",
    "unicode/unicode.cc",
    "unicode/unicode.h",
    "unicode/utf16_to_utf8_indices_map.cc",
    "unicode/utf16_to_utf8_indices_map.h",
    "unicode/utf8_decoder.h",
  ]
  deps = [ "//third_party/spdlog" ]

  # TODO: Consider checking all type conversions. These result in silent and subtle bugs. We
  # previously spent one hour debugging one.
  # configs += [ "//build/config/compiler:prevent_unsafe_narrowing" ]

  libs = []
  frameworks = []

  if (is_posix) {
    sources += [
      "files/file_posix.cc",
      "files/file_util_posix.cc",
      "rand_util_posix.cc",
    ]
  }

  if (is_mac) {
    sources += [
      "apple/ca_display_link_mac.h",
      "apple/ca_display_link_mac.mm",
      "apple/cv_display_link_mac.h",
      "apple/cv_display_link_mac.mm",
      "apple/display_link_mac.h",
      "apple/display_link_mac.mm",
      "apple/foundation_util.h",
      "apple/foundation_util.mm",
      "apple/owned_nsevent.h",
      "apple/owned_nsevent.mm",
      "apple/scoped_cftyperef.h",
      "apple/scoped_cgtyperef.h",
      "apple/scoped_typeref.h",
      "files/file_util_mac.mm",
      "message_loop/message_pump_mac.h",
      "message_loop/message_pump_mac.mm",
      "path_service_mac.cc",
      "strings/sys_string_conversions_mac.mm",
      "time/time_mac.cc",
    ]
    frameworks += [
      "Foundation.framework",
      "CoreServices.framework",
      "QuartzCore.framework",
      "AppKit.framework",
    ]
  }

  if (is_linux) {
    sources += [ "path_service_linux.cc" ]
  }

  if (is_win) {
    sources += [
      "files/file_util_win.cc",
      "path_service_win.cc",
      "rand_util_win.cc",
      "strings/sys_string_conversions_win.cc",
    ]
    libs += [ "shell32.lib" ]
  }
}

source_set("base_unittests") {
  testonly = true

  sources = [
    "containers/fixed_flat_map_unittest.cc",
    "containers/flat_map_unittest.cc",
    "containers/flat_tree_unittest.cc",
    "containers/span_util_unittest.cc",
    "files/file_path_unittest.cc",
    "hash/hash_unittest.cc",
    "location_unittest.cc",
    "memory/weak_ptr_unittest.cc",
    "no_destructor_unittest.cc",
    "numeric/safe_conversions_unittest.cc",
    "numeric/saturation_arithmetic_unittest.cc",
    "rand_util_unittest.cc",
    "strings/string_util_unittest.cc",
    "strings/utf_string_conversions_unittest.cc",
    "time/time_unittest.cc",
    "unicode/unicode_unittest.cc",
    "unicode/utf16_to_utf8_indices_map_unittest.cc",
    "unicode/utf8_decoder_unittest.cc",
  ]

  if (is_mac) {
    sources += [
      "apple/foundation_util_unittest.mm",
      "apple/scoped_cftyperef_unittest.cc",
      "strings/sys_string_conversions_mac_unittest.mm",
    ]
  }
  if (is_win) {
    sources += [ "strings/sys_string_conversions_win_unittest.cc" ]
  }

  deps = [
    ":base",
    "//third_party/googletest:gtest",
  ]
  if (is_mac) {
    deps += [ "//testing:gtest_mac" ]
  }
}

source_set("base_perftests") {
  testonly = true

  sources = [ "files/file_reader_perftest.cc" ]

  deps = [
    ":base",
    "//third_party/googletest:gtest",
  ]
}
