source_set("fx") {
  sources = [
    "fx.cc",
    "fx.h",
    "fx_internal.h",
  ]

  configs += [ "//build/config/compiler:prevent_unsafe_narrowing" ]

  if (is_mac) {
    sources += [ "core_text_backend.cc" ]
    frameworks = [
      "CoreFoundation.framework",
      "CoreGraphics.framework",
      "CoreText.framework",
    ]
  } else if (is_win) {
    sources += [
      "direct_write_backend.cc",
      "win/dwrite_globals.cc",
      "win/dwrite_globals.h",
      "win/dwrite_raster_target.cc",
      "win/dwrite_raster_target.h",
      "win/dwrite_shaping.h",
    ]
    libs = [
      "dwrite.lib",
      "gdi32.lib",
      "user32.lib",
    ]
  } else if (is_linux) {
    sources += [ "pango_backend.cc" ]
    configs += [ ":linux_font_libs" ]
  }

  deps = [
    "//base",
    "//third_party/spdlog",
  ]
}

source_set("fx_unittests") {
  testonly = true

  sources = [
    "fx_glyph_cache_unittest.cc",
    "fx_unittest.cc",
  ]

  deps = [
    ":fx",
    "//base",
    "//testing:fuzztest",
  ]
  data_deps = [ ":test_fonts" ]
}

copy("test_fonts") {
  testonly = true
  sources = [
    "test_fonts/Ahem.ttf",
    "test_fonts/far.ttf",
    "test_fonts/features.ttf",
    "test_fonts/giant.ttf",
    "test_fonts/huge_metrics.ttf",
    "test_fonts/large.ttf",
    "test_fonts/negative_metrics.ttf",
    "test_fonts/notdef_only.ttf",
    "test_fonts/text.ttf",
    "test_fonts/truncated.ttf",
    "test_fonts/zero_advance.ttf",
    "test_fonts/zero_bytes.ttf",
    "test_fonts/zero_upem.ttf",
  ]
  outputs = [ "$root_out_dir/test_fonts/{{source_file_part}}" ]
}

if (is_linux) {
  import("//build/config/linux/pkg_config.gni")

  pkg_config("linux_font_libs") {
    packages = [
      "fontconfig",
      "freetype2",
      "pangocairo",
      "pangoft2",
    ]
  }
}

executable("fx_perftest") {
  sources = [ "fx_perftest.cc" ]
  deps = [ ":fx" ]
}

executable("fx_glyph_cache_perftest") {
  sources = [ "fx_glyph_cache_perftest.cc" ]
  deps = [ ":fx" ]
}
